# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72709d2e67ea9d2acf42dce7d29c3322061b9358775987d81093a750c5a30e2a89d39d4b705062166635b3c1091bd6c19e44190681c31f58d697c9e48ef8adf2
  salva_url: http://localhost:3002

test:
  secret_key_base: d304466412590b4eff8eb14c8c08588829c4b7e60ecf3967af935adac71e33972eb79f80f6fb53ae941e952bd31b157cfee204bcef511050323f5c503cb11ad0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database_username: <%= ENV["DATABASE_USERNAME"] %>
  database_password: <%= ENV["DATABASE_PASSWORD"] %>
  salva_url: <%= ENV["SALVA_URL"] %>
  email_server: <%= ENV['EMAIL_SERVER'] %>
  email_domain: <%= ENV['EMAIL_DOMAIN'] %>
  email_user: <%= ENV['EMAIL_USER'] %>
  email_password: <%= ENV['EMAIL_PASSWORD'] %>
  ip_server: <%= ENV['IP_SERVER'] %>
